name: carpex_cihaz_sevk
description: This is a Carpex Cihaz Sevk flutter application

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  pin_code_fields: ^8.0.1
  qr_code_scanner: ^1.0.1
  modal_progress_hud_nsn: ^0.4.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  animated_splash_screen: ^1.3.0
  flutter_launcher_icons: ^0.13.1
  lottie: ^2.7.0
  connectivity_plus: ^5.0.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/sevk_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/
    - assets/images/